language: node_js
node_js:
  - "8"
install:
  - npm install eslint-changes
  - npm install
  - npm install travis-github-lint-status;
  
script:
  - ./node_modules/.bin/eslint-changes
    grunt.registerTask('travis', [
    'if-missing:esri_slurp:travis',
    'jshint'
    ]);
    - grunt travis -v
    
